### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by balogune** [Rex109/CoD4QOL#5]
Hey man. Great work. I would like to ask you can you please add an option to enable third person spectate when playing on servers or on a lan server with bots. If that doesn't work can you then make sv_cheats work on a dedicated lan server using the option in the game like you did with other stuff like fov.

Great job again man .

**Comment by Rex109** [comment]
As i stated on discord it's not necessary to add this feature to cod4qol, you just need to start your server with +devmap <yourmap>
