### ISSUE TITLE
Toggle to disable AmbientPlay music

### ISSUE THREAD

**Issue by Clipzor** [Rex109/CoD4QOL#8]
it would be amazing to be able to toggle this on and off. for example in deathrun servers you would be able to finally listen to your own music while still hearing gun sounds etc

**Comment by Rex109** [comment]
![image](https://github.com/user-attachments/assets/56bae9a9-29e9-4c1f-a0c1-993c9ec84c39)

Already implemented! 😄

**Comment by Clipzor** [comment]
sorry skill issue on my part
